name: Build rocm

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

# # ! trigger it manually
# on: 
#   workflow_dispatch:
    
env:
  DOCKER_IMAGE: ghcr.io/${{ github.repository }}/rocm

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}-rocm
  cancel-in-progress: true



jobs:
  build-and-push:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
    - name: Checkout llama.cpp repository
      uses: actions/checkout@v4
      with:
        repository: ggerganov/llama.cpp
        path: llama-repo

    - name: Checkout current repository
      uses: actions/checkout@v3
      with:
        path: local-repo

    - name: Copy Dockerfile to main repository
      run: cp local-repo/rocm/dockerfile llama-repo/

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3

    - name: Log in to GitHub Container Registry
      uses: docker/login-action@v3
      with:
        registry: ghcr.io
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}

    - name: Build and push Docker image
      uses: docker/build-push-action@v6
      with:
        context: llama-repo
        file: llama-repo/dockerfile
        push: true
        tags: |
          ${{ env.DOCKER_IMAGE }}:latest
          ${{ env.DOCKER_IMAGE }}:${{ github.sha }}

    - name: Image digest
      run: echo ${{ steps.docker_build.outputs.digest }}